### ISSUE TITLE
Rubric and Summary

### ISSUE THREAD

**Issue by ulisigi** [mrsshaw/prj-rev-bwfs-dasmoto#4]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ HTML file contains a valid link to the correct CSS file.
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 1/4
* _Comment(s):_ There are content or style omissions from the design specification in every section (header, brushes, frame, paint) of the page.
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 2/4
* _Comment(s):_ Content: HTML content matches the design specification

Tags: The tags in the HTML are not used for their intended purpose (<p> for paragraphs, <h_> for headers, etc.) in 2-3 sections.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 2/4
* _Comment(s):_ Syntax: 2-3 incorrect selectors (id, class, element type) and/or 2-3 rule sets are invalid CSS.
 
### Overall Score: 9/16
Your project Approaches Expectations. Only a few small changes will be needed in order for the project to match the design specification. Start with the image file paths and then work on the `font-family` and heading elements. For extra practice of the material learned and used for this project, try building your first personal page. As you continue to learn new things in the course, you'll be able to get extra practice by updating your personal site. By the end of the course, you'll have a great portfolio to showcase your skills and projects. 
Happy coding!

**Comment by mrsshaw** [comment]
Thank you!

**Comment by mrsshaw** [comment]
Thank you!
